#!/usr/bin/env python3
"""Generate issue templates and the readiness schema from policy/item-types.yml.

Hand-maintaining both the policy and the templates means two descriptions of one
contract, and nothing notices when they diverge. The same argument that made
bundle.yml and the catalogs generated applies here.

Outputs, all committed and all checked:

    .github/ISSUE_TEMPLATE/<type>.yml
    .github/ISSUE_TEMPLATE/config.yml
    tooling/schemas/readiness-verdict.schema.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib.inventory import ROOT, load_yaml  # noqa: E402
from lib.yamlfmt import dump  # noqa: E402

POLICY = ROOT / "policy" / "item-types.yml"
TEMPLATE_DIR = ROOT / ".github" / "ISSUE_TEMPLATE"
SCHEMA_PATH = ROOT / "tooling" / "schemas" / "readiness-verdict.schema.json"
DISCOVERY_SCHEMA = ROOT / "tooling" / "schemas" / "discovery-record.schema.json"
DISPOSAL_SCHEMA = ROOT / "tooling" / "schemas" / "disposal-record.schema.json"
ARTIFACT_POLICY = ROOT / "policy" / "artifact-policy.yml"

HEADER = (
    "# GENERATED by scripts/generate_item_templates.py from policy/item-types.yml.\n"
    "# Do not edit. Change the policy and run `make generate`.\n"
)


def acceptance_help(policy: dict) -> str:
    """The contract, shown where criteria are written rather than in a doc."""
    ac = policy.get("acceptance_criteria") or {}
    lines = [ac.get("template", "").rstrip(), "", "Rules:"]
    lines += [f"- {' '.join(r.split())}" for r in ac.get("rules") or []]
    banned = ", ".join(f'"{b["phrase"]}"' for b in ac.get("banned_phrases") or [])
    if banned:
        lines += ["", f"Rejected as unobservable: {banned}."]
    return "\n".join(lines)


def build_template(type_id: str, spec: dict, common: list[dict],
                   policy: dict | None = None) -> dict:
    body: list[dict] = [{
        "type": "markdown",
        "attributes": {"value": f"**{spec['name']}** — {spec['description']}"},
    }]
    for section in list(common) + list(spec.get("sections") or []):
        description = section["prompt"].strip()
        if section["id"] == "acceptance" and policy:
            description = f"{description}\n\n{acceptance_help(policy)}"
        body.append({
            "type": "textarea",
            "id": section["id"],
            "attributes": {
                "label": section["label"],
                "description": description,
                "placeholder": (policy.get("acceptance_criteria", {}).get("template", "")
                                if section["id"] == "acceptance" and policy else ""),
            },
            "validations": {"required": bool(section.get("required"))},
        })
    return {
        "name": spec["name"],
        "description": spec["description"],
        "labels": list(spec.get("github_labels") or []),
        "body": body,
    }


def build_schema(policy: dict) -> dict:
    verdict = policy["readiness_verdict"]
    props: dict[str, dict] = {}
    required: list[str] = []
    for name, spec in verdict["fields"].items():
        if spec["type"] == "enum":
            prop: dict = {"enum": list(spec["values"])}
        elif spec["type"] == "list":
            prop = {"type": "array", "items": {"type": "string"}}
        else:
            prop = {"type": "string", "minLength": 1}
        if spec.get("note"):
            prop["description"] = " ".join(spec["note"].split())
        props[name] = prop
        if spec.get("required"):
            required.append(name)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Readiness verdict",
        "description": (
            "Evidence for the Refining to Ready transition. "
            "Generated from policy/item-types.yml."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": required,
        "properties": props,
    }


def build_discovery_schema(artifact_policy: dict) -> dict:
    """The discovery record, from policy rather than from a copy kept here."""
    record = artifact_policy["artifacts"]["discovery_notes"]["record"]
    sources = list(record["behaviour_sources"])
    observation = {
        "type": "object",
        "required": ["statement", "source"],
        "additionalProperties": False,
        "properties": {
            "statement": {"type": "string", "minLength": 1},
            # Which of the two matters more than the observation itself.
            "source": {"enum": sources},
            "evidence": {"type": "string"},
        },
    }
    props: dict[str, dict] = {}
    for section in record["sections"]:
        if section["id"] == "current_behaviour":
            props[section["id"]] = {"type": "array", "items": observation}
        else:
            props[section["id"]] = {
                "type": "array",
                "items": {"type": "string", "minLength": 1},
                "description": " ".join(section["prompt"].split()),
            }
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Discovery record",
        "description": (
            "Bounded discovery output. Evidence, never intent: a finding "
            "becomes intended behaviour only through reconciliation. "
            "Generated from policy/artifact-policy.yml."
        ),
        "type": "object",
        "additionalProperties": False,
        # Every section is required. An absent section and an empty one mean
        # different things, and only one of them was investigated.
        "required": [s["id"] for s in record["sections"]],
        "properties": props,
    }


def build_disposal_schema(artifact_policy: dict) -> dict:
    """The disposal record, from policy rather than a copy kept here."""
    contract = artifact_policy["artifacts"]["prototype"]["disposal_record"]
    decisions = list(contract["decisions"])
    props: dict[str, dict] = {}
    required: list[str] = []
    for entry in contract["required_fields"]:
        name = entry["id"]
        if name == "decision":
            props[name] = {"enum": decisions}
        elif "values" in entry:
            props[name] = {"enum": list(entry["values"])}
        elif name in ("questions", "findings", "artifacts"):
            props[name] = {"type": "array", "items": {"type": "string", "minLength": 1}}
        else:
            props[name] = {"type": "string", "minLength": 1}
        if entry.get("note"):
            props[name]["description"] = " ".join(entry["note"].split())
        required.append(name)

    # Only meaningful when the decision is promote, and checked separately so
    # the message can say why rather than reporting a bare schema violation.
    for name in contract["promote_requires"]:
        props[name] = {"type": "string", "minLength": 1}
    for name in contract["spike_required_fields"]:
        props.setdefault(name, {"type": "string", "minLength": 1})

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Disposal record",
        "description": (
            "What a prototype or spike learned, and what becomes of it. "
            "Generated from policy/artifact-policy.yml."
        ),
        "type": "object",
        "additionalProperties": False,
        "required": required,
        "properties": props,
    }


def render(policy: dict) -> dict[Path, str]:
    common = policy.get("common_sections") or []
    out: dict[Path, str] = {}
    for type_id, spec in policy["types"].items():
        out[TEMPLATE_DIR / f"{type_id}.yml"] = HEADER + dump(
            build_template(type_id, spec, common, policy)
        )
    out[TEMPLATE_DIR / "config.yml"] = HEADER + dump({
        # Every item must be one of the defined types; a blank issue has no
        # contract and cannot be refined against one.
        "blank_issues_enabled": False,
    })
    out[SCHEMA_PATH] = json.dumps(build_schema(policy), indent=2) + "\n"
    artifact_policy = load_yaml(ARTIFACT_POLICY)
    out[DISCOVERY_SCHEMA] = json.dumps(
        build_discovery_schema(artifact_policy), indent=2) + "\n"
    out[DISPOSAL_SCHEMA] = json.dumps(
        build_disposal_schema(artifact_policy), indent=2) + "\n"
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="Fail if the generated files differ from the policy.")
    args = ap.parse_args()

    policy = load_yaml(POLICY)
    rendered = render(policy)

    if args.check:
        drift = [p for p, text in rendered.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != text]
        if drift:
            print("Item templates are stale; run scripts/generate_item_templates.py:")
            for p in drift:
                print(f"  - {p.relative_to(ROOT)}")
            return 1
        print("Item templates match policy/item-types.yml.")
        return 0

    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
