#!/usr/bin/env python3
"""Render the compatibility matrix from what the suite actually exercises.

`README.md`, `docs/installation.md`, `INSTALL-LOCAL.md`, and the `Makefile` all
named `opencode`, and a reader had no way to tell whether that was a
requirement, a default, or the only thing anybody had tried.

Derived rather than maintained. `tooling/compatibility.yml` declares which
tests prove which capability per integration; this renders it, and
`validate_source.py` refuses a claim whose test does not exist. The declaration
is reviewed once; the document follows.

Scraping the tests instead would already be wrong:
`tests/sandbox/test_claude_install.py` passes the integration as a variable, so
a scanner looking for `--integration "claude"` would report that integration
untested while its tests were passing.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib.inventory import ROOT, load_yaml  # noqa: E402

MATRIX = ROOT / "tooling/compatibility.yml"
OUT = ROOT / "docs/compatibility.md"
POLICY = ROOT / "policy/bootstrap-policy.yml"

COVERED = "yes"
UNTESTED = "not tested"


def render(compat: dict, declared: list[str]) -> str:
    capabilities = compat["capabilities"]
    claims = compat["integrations"]
    # Every integration the bundle describes appears, including ones nobody
    # has exercised. Omitting those is how "untested" reads as "unsupported"
    # or, worse, as "fine".
    names = sorted(set(declared) | set(claims))

    lines = [
        "# Compatibility",
        "",
        "<!-- Generated by scripts/generate_compat_matrix.py from",
        "tooling/compatibility.yml. Do not edit. Every cell is backed by named",
        "tests, and a claim whose test does not exist fails validation. -->",
        "",
        "The workflows do not name an agent: `integration` defaults to Spec Kit's",
        "`auto` sentinel and resolves to whichever integration the project was",
        "initialized with. This table says what has actually been exercised.",
        "",
        "| Capability | " + " | ".join(names) + " |",
        "|---|" + "---|" * len(names),
    ]
    for cap, description in capabilities.items():
        row = [f"**{cap}** — {description}"]
        for name in names:
            tests = (claims.get(name) or {}).get(cap) or []
            row.append(f"{COVERED} ({len(tests)})" if tests else UNTESTED)
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "## What no integration claims", ""]
    for key, why in (compat.get("not_claimed_by_anyone") or {}).items():
        lines.append(f"- **{key.replace('_', ' ')}** — {' '.join(why.split())}")

    lines += ["", "## The tests behind each cell", ""]
    for name in names:
        lines.append(f"### {name}")
        lines.append("")
        entries = claims.get(name) or {}
        if not entries:
            lines += [f"Nothing has been exercised under `{name}`.", ""]
            continue
        for cap in capabilities:
            tests = entries.get(cap) or []
            if not tests:
                lines.append(f"- **{cap}**: {UNTESTED}")
                continue
            lines.append(f"- **{cap}**:")
            lines += [f"  - `{t}`" for t in tests]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="Fail if the rendered document differs from the file.")
    args = ap.parse_args()

    compat = load_yaml(MATRIX)
    declared = list((load_yaml(POLICY).get("integrations") or {}).keys())
    rendered = render(compat, declared)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(f"{OUT} is stale; run scripts/generate_compat_matrix.py",
                  file=sys.stderr)
            return 1
        print(f"{OUT} is current")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
