#!/usr/bin/env python3
"""Generate the constitution shape contract into both generator surfaces.

`bootstrap-policy.yml` states what a constitution principle must look like, and
`documents.py` enforces it. Two other files described the same shape in their
own words -- `speckit.constitution.md` said only that rules "MUST be specific
enough to review or automate", and `constitution-addendum.md` said "Define
concise, actionable MUST/SHOULD rules". Neither stated the rule-first ordering
or the per-principle keyword requirement, so a generator followed the prose and
the checker followed the policy, and the freshly authored document failed the
contract its own bundle enforces (#145).

Three descriptions of one shape, and the two that drifted were the prose ones.
This makes them derived: the contract section of each file is rendered from
`product_documents.per_principle` between markers, and `--check` fails when
either is stale. The rest of both files stays hand-written -- what to write
about is an editorial choice, and only the shape is policy.

Outputs, both committed and both checked:

    bundle/.../commands/speckit.constitution.md
    bundle/.../templates/constitution-addendum.md
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib.inventory import ROOT, load_yaml  # noqa: E402

POLICY = ROOT / "policy" / "bootstrap-policy.yml"
PRESET = ROOT / "bundle/components/presets/lean-full-lifecycle-governance"
TARGETS = (
    PRESET / "commands/speckit.constitution.md",
    PRESET / "templates/constitution-addendum.md",
)

BEGIN = "<!-- BEGIN GENERATED: constitution shape -->"
END = "<!-- END GENERATED: constitution shape -->"

CONSTITUTION = ".specify/memory/constitution.md"


def per_principle(policy: dict) -> dict:
    """The one description of a principle's shape, from the one file that has it."""
    required = (policy.get("product_documents") or {}).get("required") or []
    for entry in required:
        if entry.get("path") != CONSTITUTION:
            continue
        found = entry.get("per_principle")
        if not found:
            raise SystemExit(
                f"{POLICY} describes {CONSTITUTION} with no `per_principle` "
                f"block, so there is no contract to render.")
        return found
    raise SystemExit(f"{POLICY} lists no required document at {CONSTITUTION}")


def flow(text: str) -> str:
    return " ".join(str(text).split())


def render(policy: dict) -> str:
    """The shape contract, in the policy's own words.

    Reflowed but never reworded. Paraphrasing here would recreate the defect
    one layer down: a fourth description, agreeing with the policy only until
    somebody edits one of them.
    """
    contract = per_principle(policy)
    lines = [
        BEGIN,
        "<!-- GENERATED by scripts/generate_constitution_guidance.py from",
        "     policy/bootstrap-policy.yml. Do not edit between these markers;",
        "     change the policy and run `make generate`. -->",
        "",
        "### The shape every principle takes",
        "",
        flow(contract["form"]),
        "",
        f"**Excludes.** {flow(contract['excludes'])}",
        "",
        "`documents.py` enforces exactly this, so a principle that does not "
        "take this shape fails the check before anyone reads it.",
        "",
        "**Write `SHOULD` when the source material states a preference.** It "
        "satisfies the contract without turning an expectation into an "
        "obligation. `MUST` binds the project, and only whoever governs the "
        "project may decide that -- never this generator, and never a validator "
        "reacting to a missing keyword.",
        END,
    ]
    return "\n".join(lines) + "\n"


def apply(text: str, block: str) -> str:
    """Replace the marked region, or append it when the file has none yet."""
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
                         re.DOTALL)
    if pattern.search(text):
        return pattern.sub(block, text)
    return text.rstrip("\n") + "\n\n" + block


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="Fail if either file differs from what the policy renders.")
    args = ap.parse_args()

    block = render(load_yaml(POLICY))
    stale = []
    for target in TARGETS:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        rendered = apply(current, block)
        if args.check:
            if current != rendered:
                stale.append(target)
            continue
        target.write_text(rendered, encoding="utf-8")
        print(f"wrote {target}")

    if args.check:
        for target in stale:
            print(f"{target} is stale; run "
                  f"scripts/generate_constitution_guidance.py", file=sys.stderr)
        if stale:
            return 1
        print("constitution guidance matches policy/bootstrap-policy.yml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
