#!/usr/bin/env python3
"""Generate bundle.yml from the component manifests and tooling/bundle-meta.yml.

bundle.yml is derived, not authored: it is a restatement of which components
exist and at what version, and keeping that list by hand is what let it drift
from install_dev.py, the tests, and the catalogs.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib.inventory import BUNDLE, ROOT, load_inventory  # noqa: E402
from lib.yamlfmt import dump  # noqa: E402

HEADER = """\
# GENERATED by scripts/generate_manifests.py -- do not edit.
# Component versions come from each component's own manifest; everything else
# comes from tooling/bundle-meta.yml. Run `make generate` after any change.
"""


def build_manifest(inv) -> dict:
    meta = inv.meta
    bundle = dict(meta["bundle"])
    pub = meta.get("publishing", {}) or {}
    org = pub.get("org")
    if org:
        url = f"{pub['host'].rstrip('/')}/{org}/{pub['repo']}"
        bundle["homepage"] = url
        bundle["repository"] = url

    owned = meta.get("owned_preset", {}) or {}
    presets = []
    for ext in inv.external_preset_refs():
        presets.append(dict(ext))
    for comp in inv.by_kind("preset"):
        presets.append(
            {
                "id": comp.id,
                "version": comp.version,
                "priority": owned.get("priority", 10),
                "strategy": owned.get("strategy", "append"),
            }
        )

    return {
        "schema_version": "1.0",
        "bundle": bundle,
        "requires": dict(meta["requires"]),
        "provides": {
            "presets": presets,
            "extensions": [
                {"id": c.id, "version": c.version} for c in inv.by_kind("extension")
            ],
            "workflows": [
                {"id": c.id, "version": c.version} for c in inv.by_kind("workflow")
            ],
        },
        "tags": list(meta.get("tags", [])),
    }


def render(inv) -> str:
    return HEADER + dump(build_manifest(inv))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="Fail if bundle.yml differs from what would be generated.")
    args = ap.parse_args()

    inv = load_inventory()
    want = render(inv)
    target = BUNDLE / "bundle.yml"

    if args.check:
        have = target.read_text(encoding="utf-8") if target.exists() else ""
        if have != want:
            print(f"{target.relative_to(ROOT)} is stale; run scripts/generate_manifests.py")
            return 1
        print("bundle.yml matches the component manifests.")
        return 0

    target.write_text(want, encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
